### ISSUE TITLE
dark icon

### ISSUE THREAD

**Issue by tborychowski** [sozercan/OpenInCode#8]
The macos mojave dark theme has dark background icons.
Is there a plan to make this one in dark version also?

<img width="451" alt="screenshot 2018-07-20 at 14 18 01" src="https://user-images.githubusercontent.com/392513/43004450-bb7f5df6-8c27-11e8-950e-233411cf7649.png">

**Comment by tborychowski** [comment]
Hi, I made the icon, just don't know how to build it.
It doesn't have to be packed into the single app (containing both light & dark version).
I'd be perfectly happy with 2 separate apps - 1 with light bg and 1 with dark.
Would you be able to build it (or add description to the README how to build it?)

Here's the zip with icon: 
[vscode-dark.zip](https://github.com/sozercan/OpenInCode/files/2252709/vscode-dark.zip)

It's hi-res and should be aligned with the rest of the toolbar icons.
Here's how it looks:
![vscode_512x512](https://user-images.githubusercontent.com/392513/43571980-40777332-9636-11e8-9dc7-a51ab481dfab.png)

**Comment by MirkoLenz** [comment]
The icon looks great, thanks for sharing it!

Until it is implemented by the project owner, you could use the following workaround:

- Right click onto the app "Open in Code" and select "Get Info".
- Drag your new dark icon and drop it onto the old application icon in the top left of the inspector window.
- You should now have the new icon in the Finder menu bar.

Hope it helps.

**Comment by tborychowski** [comment]
Thanks @MirkoLenz!
I know that trick, but somehow I didn't think of it! 😀
Works perfectly!

**Comment by ZaynJarvis** [comment]
Thank you guys for this icon and trick!

**Comment by tborychowski** [comment]
Updated icon (as it seems that native toolbar buttons are a bit shorter now): 
[vscode.zip](https://github.com/sozercan/OpenInCode/files/2580151/vscode.zip)

**Comment by sozercan** [comment]
thanks so much @tborychowski! I updated the release with the dark mode icon: 
https://github.com/sozercan/OpenInCode/releases/download/v1.0/OpenInCodeDark.zip

**Comment by pushqrdx** [comment]
@tborychowski What is that other icon that looks like terminal? 😄

**Comment by bbilginn** [comment]
hi @tborychowski, can you also share the svg file for the terminal? 
hi @pushqrdx maybe it looks like this https://github.com/es-kumagai/OpenTerminal but icon is good drawn icon
thanks everyone

**Comment by tborychowski** [comment]
@pushqrdx @bbilginn, no this was done for [open-in-iterm](https://github.com/jakshin/open-in-iterm/issues/2).

I've redone both icons myself (in sketch).
I can share the sketch file if anyone's interested (just send me a @gmail).

**Comment by stevemoser** [comment]
How do I use home brew to install the dark version?
