### ISSUE TITLE
can not add Open-in-code into finder-toolbar

### ISSUE THREAD

**Issue by sunzd116** [sozercan/OpenInCode#9]
I cannot add Open-in-code into finder toolbar in macOS Mojave

**Comment by AnalyzePlatypus** [comment]
Same. 
The app cannot be dropped into the toolbar in Mojave 10.14

**Comment by AnalyzePlatypus** [comment]
I found a fix!
In Mojave, hold down `Option` + `Command` while dragging the app unto the toolbar.
(The toolbar is not customizable without these modifiers.)

**Comment by AnalyzePlatypus** [comment]
This issue can be closed.
